"""message

Revision ID: 136cab86ca43
Revises: 8424fe926d99
Create Date: 2022-10-05 12:08:23.469865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '136cab86ca43'
down_revision = '8424fe926d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models_table',
    sa.Column('id_name', sa.String(), nullable=False),
    sa.Column('namespace', sa.JSON(), nullable=True),
    sa.Column('docs', sa.JSON(), nullable=True),
    sa.Column('vars_exposed', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id_name')
    )
    op.drop_table('models')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id_name', sa.VARCHAR(), nullable=False),
    sa.Column('namespace', sqlite.JSON(), nullable=True),
    sa.Column('docs', sqlite.JSON(), nullable=True),
    sa.Column('vars_exposed', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id_name')
    )
    op.drop_table('models_table')
    # ### end Alembic commands ###
