"""added username for auth password flow

Revision ID: 1cc40dbb5f37
Revises: 88cc71d88c07
Create Date: 2022-09-27 11:36:39.463181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc40dbb5f37'
down_revision = '88cc71d88c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'username')
    # ### end Alembic commands ###
