"""test-update

Revision ID: 3822e5a0523a
Revises: c0fca1b550f1
Create Date: 2022-05-25 11:13:57.379210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3822e5a0523a'
down_revision = 'c0fca1b550f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
