"""message

Revision ID: 8424fe926d99
Revises: 1cc40dbb5f37
Create Date: 2022-10-03 12:29:24.221918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8424fe926d99'
down_revision = '1cc40dbb5f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('vars_exposed', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'vars_exposed')
    # ### end Alembic commands ###
