"""Added params column

Revision ID: ac851f31dcdc
Revises: fe33277db90b
Create Date: 2022-08-03 10:57:03.539165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac851f31dcdc'
down_revision = 'fe33277db90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Simulation', sa.Column('params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Simulation', 'params')
    # ### end Alembic commands ###
