"""first revision

Revision ID: c0fca1b550f1
Revises: 
Create Date: 2022-05-25 01:02:46.074101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fca1b550f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Models',
    sa.Column('id_name', sa.String(), nullable=False),
    sa.Column('namespace', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id_name')
    )
    op.create_table('Simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=30), nullable=False),
    sa.Column('simulation_name', sa.String(length=30), nullable=False),
    sa.Column('csv_path', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('json_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Simulation')
    op.drop_table('Models')
    # ### end Alembic commands ###
