"""num_student column

Revision ID: f55fa3e9ac97
Revises: 
Create Date: 2022-09-21 18:15:45.090477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55fa3e9ac97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classroom', sa.Column('num_students', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classroom', 'num_students')
    # ### end Alembic commands ###
